language: cpp
dist: xenial
language: cpp
services:
  - xvfb

#limit to git depth to 1 because don't use any git command in this script
git:
  depth: 1
before_install:
#g++ 8
- echo 'Installing G++ 8'
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
- sudo apt-get install udev build-essential libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew-dev libjpeg-dev libxi-dev
- sudo apt-get install libxinerama-dev libxcursor-dev 
- sudo apt-get install libudev-dev libglu1-mesa-dev libsecret-1-dev libnotify-dev
- sudo apt-get install checkinstall libtiff5-dev ubuntu-restricted-extras freeglut3 freeglut3-dev libcairo2-dev
- sudo apt-get install libgconf2-dev


script:
- echo 'Generating makefile'
- cmake . 
- make all
- make install
- ls -l
- tar -zcf $TRAVIS_BUILD_DIR.tar.gz $TRAVIS_BUILD_DIR
- ls -l

deploy:
  provider: releases
  token: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR.tar.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true
    