language: cpp
dist: xenial
language: cpp
services:
  - xvfb

os:
  - linux
  - osx

#limit to git depth to 1 because don't use any git command in this script
git:
  depth: 1


before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update                             ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openal-soft                ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5                        ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export Qt5_DIR=$(brew --prefix)/opt/qt5 ; fi
#g++ 8
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo 'Installing G++ 8';fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq;fi
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-8;fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8";fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50;fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install qtbase5-dev;fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install udev build-essential libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew-dev libjpeg-dev libxi-dev;fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libxinerama-dev libxcursor-dev ;fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libudev-dev libglu1-mesa-dev libsecret-1-dev libnotify-dev;fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install checkinstall libtiff5-dev ubuntu-restricted-extras freeglut3 freeglut3-dev libcairo2-dev;fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libgconf2-dev;fi
# MacOS install : 
# brew install openal-soft
# brew install qt5
# export Qt5_DIR=$(brew --prefix)/opt/qt5


script:
- echo 'Generating makefile'
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release
- make package
- export TRAVIS_FILE=$(ls *.tar.gz)
- ls -l

deploy:
  provider: releases
  token: $GITHUB_API_KEY
  file: $TRAVIS_FILE
  skip_cleanup: true
  draft: true
  on:
    tags: true
    