version: '{build}'

environment:
  ZLIB_VERSION: 1.2.8.4
  
branches:
  only:
  - master
  - CI_update_and_fix
 

image:
- Visual Studio 2017

configuration:
- Release   

platform:
- x86
- x64

install:
- git submodule update --init --recursive

  
before_build:
- cmd: |-
    if %platform%==x64 (    set CMAKE_GENERATOR="Visual Studio 15 2017 Win64" ) else (   set CMAKE_GENERATOR="Visual Studio 15 2017")   
    mkdir build
    cd build
    cmake --version
    echo %CMAKE_GENERATOR%
    cmake .. -G %CMAKE_GENERATOR%
    
build_script:
- cmd : |- 
    cmake --build . --config %configuration%
    cmake --build . --config %configuration% --target INSTALL

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - Sugarbox/
    - CPCCore/

