version: '{build}'

environment:
  ZLIB_VERSION: 1.2.8.4
  
branches:
  only:
  - master
  - tweak_ci_dev
  

image:
- Visual Studio 2017

configuration:
- Release   

platform:
- x86
- x64

install:
- git submodule update --init --recursive
- if %platform%==x64 ( set QTDIR=C:\Qt\5.13.2\msvc2017_64) else ( set QTDIR=C:\Qt\5.13.2\msvc2017 )  
- set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  
before_build:
- cmd: |-
    if %platform%==x64 (    set CMAKE_GENERATOR="Visual Studio 15 2017 Win64" ) else (   set CMAKE_GENERATOR="Visual Studio 15 2017")   
    mkdir build
    cd build
    cmake --version
    echo %CMAKE_GENERATOR%
    cmake .. -G %CMAKE_GENERATOR%
    
build_script:
- cmd : |-
    cmake --build . --config %configuration% --target INSTALL
    cmake --build . --config %configuration% --target PACKAGE

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - Sugarbox/c
    - CPCCore/

after_build:
- cmd : |- 
    cpack.exe -C Release --config ./CPackConfig.cmake

artifacts:
- path: 'build/*.zip'
  name: Zipfiles
  type: zip

deploy:
  release: Sugarbox-v2.0.$(appveyor_build_version)
  description: Sugarbox V2, for Windows.
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME) 
  auth_token:
    secure: 3xDp6ujDQwOa9KJgf7AkK+UjFw2FHDRhwf93PwBUqpNUKn7x93L06Yy5N5YnehvF
  artifact: Zipfiles
  draft: true
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true