version: '{build}'

environment:
  ZLIB_VERSION: 1.2.8.4
  
branches:
  only:
  - master
  - release_management
  

image:
- Visual Studio 2017

configuration:
- Release   

platform:
- x86
- x64

install:
- git submodule update --init --recursive

  
before_build:
- cmd: |-
    if %platform%==x64 (    set CMAKE_GENERATOR="Visual Studio 15 2017 Win64" ) else (   set CMAKE_GENERATOR="Visual Studio 15 2017")   
    mkdir build
    cd build
    cmake --version
    echo %CMAKE_GENERATOR%
    cmake .. -G %CMAKE_GENERATOR%
    
build_script:
- cmd : |- 
    cmake --build . --config %configuration%
    cmake --build . --config %configuration% --target INSTALL

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - Sugarbox/
    - CPCCore/

after_build:
- cmd : |- 
    set artifact_name=SugarboxV2_%platform%.zip
    7z a -r -tzip %artifact_name% %APPVEYOR_BUILD_FOLDER%\build\Sugarbox\%configuration%\*.*
    appveyor PushArtifact %artifact_name%

deploy:
  release: Sugarbox-v2.0.$(appveyor_build_version)
  description: Sugarbox V2, for Winwods.
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME) 
  auth_token:
    secure: 3xDp6ujDQwOa9KJgf7AkK+UjFw2FHDRhwf93PwBUqpNUKn7x93L06Yy5N5YnehvF
  artifact: SugarboxV2_x86.zip,SugarboxV2_x64.zip
  draft: true
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true