version: '{build}'

environment:
  ZLIB_VERSION: 1.2.8.4
  
branches:
  only:
  - master
 

image:
- Visual Studio 2017
- Ubuntu1804

configuration:
- Release   

platform:
- x86
- x64

install:
- git submodule init 
- git submodule update
- sh: |- 
    echo 'Update to gcc8'
    sudo update-alternatives --set gcc /usr/bin/gcc-8

  
before_build:
- cmd: |-
    if %platform%==x64 (    set CMAKE_GENERATOR="Visual Studio 15 2017 Win64" ) else (   set CMAKE_GENERATOR="Visual Studio 15 2017")   
    mkdir build
    cd build
    cmake --version
    echo %CMAKE_GENERATOR%
    cmake .. -G %CMAKE_GENERATOR%
- sh: |-
    mkdir build
    cd build
    cmake --version
    cmake .. 

    
build_script:
- cmd : |- 
    cmake --build . --config %configuration%
    cmake --build . --config %configuration% --target INSTALL
- sh: |-
    make all

after_build:
- cmd : |- 
    set artifact_name=SugarConvDsk_%platform%.zip
    7z a %artifact_name% %APPVEYOR_BUILD_FOLDER%\build\SugarConvDsk\%configuration%\SugarConvDsk.exe
    appveyor PushArtifact %artifact_name%
- sh:  |-
    artifact_name=$APPVEYOR_BUILD_FOLDER/build/SugarConvDsk/$configuration/SugarConvDsk_$PLATFORM.gz
    gzip -k $APPVEYOR_BUILD_FOLDER/build/SugarConvDsk/$configuration/SugarConvDsk
    mv $APPVEYOR_BUILD_FOLDER/build/SugarConvDsk/$configuration/SugarConvDsk.gz $artifact_name
    appveyor PushArtifact $artifact_name

test_script:
- cmd:  |-
    cd c:\projects\SugarConvDsk\build\Tests
    cd %configuration%
    Tests.exe
- sh:  |-
    cd $APPVEYOR_BUILD_FOLDER/build/Tests
    make install
    chmod +777 SugarConvDsk
    ./Tests

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - SugarConvDsk/
    - CPCCoreEMu/
    - Tests/

deploy:
  release: SugarConvDsk-v1.0.$(appveyor_build_version)
  description: SugarConvDsk tool. Zip are for windows system, .gz for linux.
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME) 
  auth_token:
    secure: /Nr3QtuzpAw6S9iRX/KJ5f3RGXpx9xiuhrxz+jLV5aVSVrhNPX2ZTFaNn0ToOBDx
  artifact: SugarConvDsk_x86.gz,SugarConvDsk_x64.gz,SugarConvDsk_x86.zip,SugarConvDsk_x64.zip
  draft: false
  prerelease: true
  on:
    APPVEYOR_REPO_TAG : true       # deploy on tag push only