name: MacOS

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on:  macOS-latest
          
    steps:
    - uses: actions/checkout@v3
          
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.14.2'
        target: 'desktop'
        arch: ${{ matrix.qt_version }}
        install-deps: 'true'
        
    - name: Install Third Party
      run: |
        brew install openal-soft 
        brew install qt5
        export Qt5_DIR=$(brew --prefix)/opt/qt5


    - name: Checkout submodules
      run: git submodule update --init --recursive 

    - name: Configure CMake
      run: |
        echo 'Generating makefile'
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make package
        ls -l
      
    - name: Archive zip
      uses: actions/upload-artifact@v3
      with:
          name: SugarboxV2MacOS
          path: ${{github.workspace}}/build/*.tar.gz
          
          
          
