name: MacOS

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on:  macOS-latest

            other_installer: 'brew install openal-soft && brew install qt5 && export Qt5_DIR=$(brew --prefix)/opt/qt5'
            build_folder: /build 
            install_folder: /install
          - os: windows-latest
            qt_version: 'win32_msvc2017'
            cmake_arg: '-AWin32 -DGENERATE_UNITTESTS=TRUE' 
            other_installer: 'echo No more installer needed'
            build_folder: \build 
            install_folder: \install
          
    steps:
    - uses: actions/checkout@v3
          
    - name: Install Third Party
      run: |
        brew install openal-soft 
        brew install qt5
        export Qt5_DIR=$(brew --prefix)/opt/qt5
        
    - name: Checkout submodules
      run: git submodule update --init --recursive 

    - name: Configure CMake
      run: |
        echo 'Generating makefile'
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make package
        ls -l
      
    - name: Archive zip
      uses: actions/upload-artifact@v3
      with:
          name: SugarboxV2MacOS
          path: ${{github.workspace}}/build/*.tar.gz
          
          
          
