name: Release

on:
  workflow_dispatch :
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      Sugarbox_version: "${{ steps.vars.outputs.version }}"
    steps:
      - name: Get tag/branch name
        id: vars
        run: |
          echo "version=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
          
  call-workflow-windows:
    needs: extract-version
    uses:  ./.github/workflows/windows.yml
    with:
      version: ${{ needs.extract-version.outputs.Sugarbox_version }}
  call-workflow-ubuntu:
    needs: extract-version
    uses:  ./.github/workflows/ubuntu.yml
    with:
      version: ${{ needs.extract-version.outputs.Sugarbox_version }}
  call-workflow-macos:
    needs: extract-version
    uses:  ./.github/workflows/macos.yml
    with:
      version: ${{ needs.extract-version.outputs.Sugarbox_version }}
  deploy:
    runs-on: ubuntu-latest
    needs: [call-workflow-windows, call-workflow-ubuntu, call-workflow-macos]
    steps:
      - name: Prepare Release directory
        run: |
          mkdir release_bin
          cd release_bin
          
      - name: Download artifact Ubuntu
        uses: actions/download-artifact@v3
        id: art-ubuntu
        with:
          name: SugarboxV2Ubuntu
          
      - name: Download artifact Windows
        uses: actions/download-artifact@v3
        id: art-windows
        with:
          name: SugarboxV2Win32
          
      - name: Download artifact MacOS
        uses: actions/download-artifact@v3
        id: art-macos
        with:
          name: SugarboxV2MacOS

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{steps.art-ubuntu.outputs.download-path}}/*
            
          
