name: Ubuntu

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_call:
    inputs: 
      version:
        description: 'Version to build'
        default: 2.x.x
        type: string

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Environement
      run: |
        sudo apt-get update
        sudo apt install qt6-base-dev --fix-missing
        sudo apt-get install libqt6websockets6-dev --fix-missing
        sudo apt-get install udev build-essential libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew-dev libjpeg-dev libxi-dev --fix-missing
        sudo apt-get install libxinerama-dev libxcursor-dev --fix-missing
        sudo apt-get install libudev-dev libglu1-mesa-dev libsecret-1-dev libnotify-dev --fix-missing
        sudo apt-get install checkinstall libtiff5-dev ubuntu-restricted-extras freeglut3-dev libcairo2-dev --fix-missing
        sudo apt-get install libgconf2-dev --fix-missing

    - name: Checkout submodules
      run: git submodule update --init --recursive 
      
    - name: Configure CMake
      run: |
        echo 'Generating makefile'
        mkdir build
        cd build
        echo 'Version : '  ${{ inputs.version }}
        cmake .. -DCMAKE_BUILD_TYPE=Release -DSUGARBOX_VERSION='${{ inputs.version }}'
        make package
        ls -l

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
          name: SugarboxV2Ubuntu
          path: ${{github.workspace}}/build/*.tar.gz
